stages: 
  - build
  - deploy

image: node:12.13.0-alpine

build:
  stage: build
  script:
    - echo ${APP_VERSION}

deploy:
  stage: deploy
  script:
    - npm i -g firebase-tools
    - firebase deploy --token $FIREBASE_TOKEN
  only:
    - tags
