stages: 
  - build
  - deploy

image: node:12.13.0-alpine

build:
  stage: build
  script:
    - '%CURL% --header "PRIVATE-TOKEN: %ACCESS_TOKEN%" --insecure https://source.example.com/api/v4/projects/id/repository/tags/%CI_COMMIT_TAG% | %JQ% ".release.description" > %TEMPFILE%'
    - cat %TEMPFILE%
deploy:
  stage: deploy
  script:
    - npm i -g firebase-tools
    - firebase deploy --token $FIREBASE_TOKEN
  only:
    - tags
